# Generated by Django 3.1.1 on 2020-09-28 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0002_auto_20200928_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='commentpermission',
            field=models.IntegerField(default=0, verbose_name='commentpermission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='communityvisibilitystate',
            field=models.IntegerField(default=0, verbose_name='communityvisibilitystate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='lastlogoff',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 20, 42, 19, 815933, tzinfo=utc), verbose_name='lastlogoff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='personastate',
            field=models.IntegerField(default=0, verbose_name='personastate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='profilestate',
            field=models.IntegerField(default=0, verbose_name='profilestate'),
            preserve_default=False,
        ),
    ]
