# Generated by Django 3.1.1 on 2020-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0003_auto_20200928_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='primaryclanid',
            field=models.IntegerField(blank=True, null=True, verbose_name='primaryclanid'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='realname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='realname'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='timecreated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='timecreated'),
        ),
    ]
