# Generated by Django 3.1.1 on 2020-09-28 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0005_auto_20200928_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='last_update',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
