# Generated by Django 3.1.1 on 2020-09-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0006_auto_20200928_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='primaryclanid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='primaryclanid'),
        ),
    ]
