# Generated by Django 3.1.1 on 2020-09-27 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_since', models.DateTimeField(verbose_name='friends since')),
                ('relationship', models.CharField(max_length=50, verbose_name='relationship')),
            ],
        ),
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='SteamGame')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='SteamGame')),
                ('header_url', models.CharField(blank=True, max_length=500, null=True)),
                ('header', models.ImageField(blank=True, null=True, upload_to='SteamGame')),
                ('background_url', models.CharField(blank=True, max_length=500, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='SteamGame')),
                ('has_detailed_info', models.BooleanField(default=False)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('about_the_game', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.BigIntegerField()),
                ('personaname', models.CharField(max_length=255)),
                ('profileurl', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=500)),
                ('avatarmedium', models.CharField(max_length=500)),
                ('avatarfull', models.CharField(max_length=500)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('ownedGames', models.CharField(blank=True, max_length=1000000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('friends', models.ManyToManyField(related_name='_steamuser_friends_+', through='steambroapp.Friendship', to='steambroapp.SteamUser')),
            ],
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_steamuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_friend', to='steambroapp.steamuser', verbose_name=''),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_steamuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_origin', to='steambroapp.steamuser', verbose_name=''),
        ),
    ]
