# Generated by Django 3.1.1 on 2020-09-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='steamid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
