# Generated by Django 3.1.1 on 2020-09-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0004_auto_20200928_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steamuser',
            old_name='ownedGames',
            new_name='owned_games_list',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='games',
            field=models.ManyToManyField(to='steambroapp.SteamGame', verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='friends',
            field=models.ManyToManyField(related_name='_steamuser_friends_+', through='steambroapp.Friendship', to='steambroapp.SteamUser', verbose_name='friends'),
        ),
    ]
