# Generated by Django 3.1.1 on 2020-09-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0008_auto_20200929_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='communityvisibilitystate',
            field=models.IntegerField(default=1, verbose_name='communityvisibilitystate'),
        ),
    ]
