# Generated by Django 3.1.1 on 2020-09-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0010_auto_20200929_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='personastate',
            field=models.IntegerField(default=0, verbose_name='personastate'),
        ),
    ]
