# Generated by Django 3.1.1 on 2021-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0012_auto_20200929_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='steamid_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
