# Generated by Django 4.0.1 on 2022-01-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0013_steamuser_steamid_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='friends',
            field=models.ManyToManyField(through='steambroapp.Friendship', to='steambroapp.SteamUser', verbose_name='friends'),
        ),
    ]
