# Generated by Django 4.0.2 on 2022-02-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0014_alter_steamuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='avatarfull',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='avatarmedium',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='steambroapp.SteamGame', verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='personaname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='profileurl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
