# Generated by Django 4.0.2 on 2022-02-06 00:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0015_alter_steamuser_avatar_alter_steamuser_avatarfull_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friend_since',
            new_name='friends_since',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='from_steamuser_id',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_steamuser_id',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_steamuser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='from_steamusers', to='steambroapp.steamuser', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_steamuser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='to_steamusers', to='steambroapp.steamuser', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='friendships',
            field=models.ManyToManyField(related_name='related_to', through='steambroapp.Friendship', to='steambroapp.SteamUser', verbose_name='friends'),
        ),
    ]
