# Generated by Django 4.0.2 on 2022-02-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0016_rename_friend_since_friendship_friends_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamgame',
            name='appid',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='personaname',
            field=models.CharField(blank=True, help_text="The player's persona name (display name)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='steamid',
            field=models.BigIntegerField(help_text='64bit SteamID of the user', unique=True),
        ),
    ]
