# Generated by Django 4.0.2 on 2022-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0017_alter_steamgame_appid_alter_steamuser_personaname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='avatarhash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='loccountrycode',
            field=models.CharField(blank=True, help_text="If set on the user's Steam Community profile, The user's country of residence, 2-character ISO country code", max_length=5, null=True, verbose_name='country coude'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='locstatecode',
            field=models.CharField(blank=True, help_text="If set on the user's Steam Community profile, The user's state of residence", max_length=50, null=True, verbose_name='state'),
        ),
    ]
