# Generated by Django 4.0.3 on 2022-04-09 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0018_steamuser_avatarhash_steamuser_loccountrycode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_system_group', models.BooleanField(help_text='If this group is one of the defaults')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steambroapp.steamgame')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steambroapp.gamegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steambroapp.steamuser')),
            ],
        ),
    ]
