# Generated by Django 4.0.3 on 2022-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0019_gamegroup_usergamegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamgame',
            name='header',
        ),
        migrations.AddField(
            model_name='steamgame',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
