# Generated by Django 4.0.4 on 2022-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0020_remove_steamgame_header_steamgame_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamgame',
            name='background',
        ),
        migrations.RemoveField(
            model_name='steamgame',
            name='background_url',
        ),
        migrations.RemoveField(
            model_name='steamgame',
            name='header_url',
        ),
        migrations.RemoveField(
            model_name='steamgame',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='steamgame',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='friendships_are_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='friendships_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
