# Generated by Django 4.0.4 on 2022-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steambroapp', '0022_steamuser_summary_updated_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_steamuser', 'to_steamuser'), name='unique_friendship'),
        ),
    ]
