# Generated by Django 2.1.5 on 2019-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.BigIntegerField()),
                ('personaname', models.CharField(max_length=255)),
                ('profileurl', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=500)),
                ('avatarmedium', models.CharField(max_length=500)),
                ('avatarfull', models.CharField(max_length=500)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
