# Generated by Django 2.1.5 on 2019-02-04 15:08

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('steam_img_icon_url', models.CharField(max_length=500)),
                ('img_icon', models.ImageField(upload_to='')),
                ('steam_img_logo_url', models.CharField(max_length=500)),
                ('img_logo', models.ImageField(upload_to='')),
                ('has_detailed_info', models.BooleanField(help_text='If this is false, an API request to app api will be made.', verbose_name=False)),
            ],
        ),
        migrations.AddField(
            model_name='steamuser',
            name='ownedGames',
            field=models.CharField(blank=True, max_length=1000000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
