# Generated by Django 2.1.5 on 2019-02-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_auto_20190204_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steamgame',
            old_name='steam_img_icon_url',
            new_name='img_icon_url',
        ),
        migrations.RenameField(
            model_name='steamgame',
            old_name='steam_img_logo_url',
            new_name='img_logo_url',
        ),
    ]
