# Generated by Django 2.1.5 on 2019-02-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_auto_20190204_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamgame',
            name='has_detailed_info',
            field=models.BooleanField(default=False),
        ),
    ]
