# Generated by Django 2.1.5 on 2019-02-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0004_auto_20190204_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamgame',
            name='img_icon',
            field=models.ImageField(upload_to='SteamGame'),
        ),
        migrations.AlterField(
            model_name='steamgame',
            name='img_logo',
            field=models.ImageField(upload_to='', verbose_name='SteamGame'),
        ),
    ]
