# Generated by Django 2.1.5 on 2019-02-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0005_auto_20190204_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='friends',
            field=models.ManyToManyField(to='steam.SteamUser'),
        ),
        migrations.AlterField(
            model_name='steamgame',
            name='img_logo',
            field=models.ImageField(upload_to='SteamGame'),
        ),
    ]
